import "./globals.css";
import { Inter } from "next/font/google";
import ToasterClient from "@/components/ui/ToasterClient";
import NavBar from "@/components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Orbital 2023",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ToasterClient />
        <main className="bg-slate-950 w-full h-screen flex flex-row">
          <NavBar />
          <div className="w-full h-screen">{children}</div>
        </main>
      </body>
    </html>
  );
}
