import "./globals.css";
import { Inter } from "next/font/google";
import ToasterClient from "@/components/ui/ToasterClient";
import NavBar from "@/components/NavBar";
// import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Orbital 2023",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark h-full overflow-hidden">
      <body className={inter.className}>
        {/* show DOM content after loaded to prevent dark mode flickering */}
        {/* <Script src='/theme.js' strategy='afterInteractive' /> */}
        <ToasterClient />
        <main className="flex w-full flex-row bg-white transition-colors duration-500 dark:bg-slate-950">
          <NavBar />
          <div className="h-screen w-full">{children}</div>
        </main>
      </body>
    </html>
  );
}
